call ana2obj alg	
call ana2obj allocm	
call ana2obj chk86	
call ana2obj cmdlines	
call ana2obj cntvsync	
call ana2obj lfn	
call ana2obj deb	
call ana2obj deb_dmp	
call ana2obj fname	
call ana2obj fnm_aext	
call ana2obj fnm_cext	
call ana2obj fnm_eext	
call ana2obj fnm_gext	
call ana2obj fnm_gtad	
call ana2obj fnm_mvop	
call ana2obj fpal	
call ana2obj g98	
call ana2obj pri	
call ana2obj pri_chr	
call ana2obj pri_dw	
call ana2obj pri_hex2	
call ana2obj pri_hex4	
call ana2obj pri_hex8	
call ana2obj pri_int	
call ana2obj pri_s	
call ana2obj pri_word	
call ana2obj readln	
call ana2obj rpal	
call ana2obj rpl_getp	
call ana2obj rpl_gett	
call ana2obj rpl_setp	
call ana2obj rpl_sett	
call ana2obj sbr_allc	
call ana2obj sbr_crea	
call ana2obj sbr_dele	
call ana2obj sbr_errf	
call ana2obj subr	
call ana2obj sbr_open	
call ana2obj sbr_prex	
call ana2obj sbr_pris	
call ana2obj sbr_read	
call ana2obj sbr_renm	
call ana2obj sbr_seek	
call ana2obj sbr_writ	
call ana2obj std_psiz	
call ana2obj str	
call ana2obj str_atol	
call ana2obj str_cmp	
call ana2obj str_cpy	
call ana2obj str_dect	
call ana2obj str_dw2a	
call ana2obj str_dw2h	
call ana2obj str_htol	
call ana2obj str_icmp	
call ana2obj str_len	
call ana2obj str_ltoa	
call ana2obj str_ltoh	
call ana2obj str_ncut	
call ana2obj str_nlck	
call ana2obj str_sepl	
call ana2obj str_sp2t	
call ana2obj str_t2sp	
call ana2obj str_trim	
call ana2obj str_uplo	
call ana2obj wildcmp	
call ana2obj writln	
call ana2obj direntry	
call as2obj  pri_fmt	

wlib -c alibs.lib @alib.lin

md asm
md obj
move *.asm asm\
move *.obj obj\
